-- Starting content: the 100-day program's projects. Everything here is editable in the admin section.
insert into profile (id, name, headline, bio, github_url) values (
  1,
  'sasukeaizen7',
  'Data engineer: pipelines, warehouses and streaming, on real public data',
  'Eleven data engineering projects and 18 SQL analytics projects built over a 100-day program, from a Python ETL to a live, monitored pipeline. Everything runs locally with Docker and is checked by CI on every push.',
  'https://github.com/sasukeaizen7'
);

insert into projects (slug, title, summary, description, category, period, tags, highlights, repo_url, color, featured, sort_order) values
('velib-live-pipeline', 'Vélib'' Paris: live pipeline',
 'Live bike availability for ~1,500 Paris stations: API → Airflow → S3 → warehouse → dbt → dashboard, with monitoring and alerts.',
 'Every 10 minutes the pipeline snapshots the whole Vélib'' network from its live GBFS API, keeps every snapshot in an immutable S3 raw zone, loads them into a Postgres warehouse, models them with dbt and serves a live Streamlit dashboard.

It checks its own health: freshness tests, data-quality tests and alerts when a feed goes stale. Infrastructure is in Terraform and every push runs CI.',
 'Data pipelines', 'Days 85–98 · final project',
 '{Airflow,S3,Postgres,dbt,Streamlit,Terraform,Monitoring}',
 '{"A range test caught two 410-dock stations: temporary event megastations at Invalides and Concorde, now their own category","Snapshots are immutable, so any day can be reloaded from the raw zone"}',
 'https://github.com/sasukeaizen7/portfolio/tree/main/11-final-project', '#2dd4bf', true, 1),
('python-etl', 'Python ETL',
 'Weather API → Parquet lake → Postgres with retries, validation and idempotent upserts.',
 'A small but production-shaped batch ETL. It pulls daily weather for 5 French cities from the Open-Meteo archive API, validates it, writes it to a Parquet lake partitioned by city and month, and upserts it into Postgres.',
 'Data pipelines', 'Days 10–21', '{Python,pandas,Parquet,Postgres,pytest,Docker}',
 '{"Retries with exponential backoff and timeouts","Bad batches are refused, never half-loaded","COPY + upsert: re-running a day changes nothing"}',
 'https://github.com/sasukeaizen7/portfolio/tree/main/01-python-etl', '#60a5fa', false, 2),
('data-modeling', 'E-commerce star schema',
 'A dimensional model for 1M real invoice lines, with a tested SCD type 2 merge and a Snowflake version.',
 'Facts and dimensions for the UCI Online Retail II dataset (2009–2011). It is the schema that the ingestion pipeline loads and the dbt project rebuilds.',
 'Data pipelines', 'Days 22–28', '{"Dimensional modeling","SCD 2",Snowflake,SQL}',
 '{"Slowly changing customer dimension, tested on its edge cases"}',
 'https://github.com/sasukeaizen7/portfolio/tree/main/02-data-modeling', '#a78bfa', false, 3),
('ingestion-pipeline', 'E-commerce ingestion pipeline',
 'Two years of real sales replayed one trading day at a time into a star schema: transactional, idempotent, audited.',
 'A daily batch pipeline that replays 1.04M invoice lines one trading day at a time. Every batch runs in one transaction, can be re-run safely, is written to an audit table and passes 6 data-quality checks before it commits.',
 'Data pipelines', 'Days 29–35 · project 1', '{Python,DuckDB,Postgres,Docker}',
 '{"3,393 \"cancellations\" turned out to be stock write-offs, found by cross-checking with the dbt project"}',
 'https://github.com/sasukeaizen7/portfolio/tree/main/03-project-1-ingestion', '#f472b6', false, 4),
('dbt-analytics', 'dbt analytics',
 'Sources, seeds, an incremental model with a contract, a snapshot, macros and 56 tests.',
 'A dbt project that rebuilds the retail warehouse from the raw layer and adds analytics marts. Its tests also cross-check the Python pipeline: two independent implementations of the same model must agree.',
 'Data pipelines', 'Days 32–42', '{dbt,SQL,Postgres,"Unit tests"}',
 '{"56 tests including dbt unit tests","Found a real bug in Project 1"}',
 'https://github.com/sasukeaizen7/portfolio/tree/main/04-dbt-analytics', '#fb923c', false, 5),
('airflow-stocks', 'Airflow stock pipeline',
 'Two Airflow 3 DAGs: a sensor, dynamic task mapping, XComs, retries and Asset-driven scheduling.',
 'Daily prices for 8 US and French stocks are fetched in parallel with dynamic task mapping, validated and upserted into Postgres. A second DAG refreshes a per-symbol report whenever new prices land, triggered by an Airflow Asset.',
 'Data pipelines', 'Days 41–49', '{"Airflow 3",Python,Postgres}',
 '{"Sensor in reschedule mode frees the worker slot while waiting"}',
 'https://github.com/sasukeaizen7/portfolio/tree/main/05-airflow-stock-pipeline', '#facc15', false, 6),
('pyspark-taxi', 'PySpark on 20M taxi trips',
 'Partitioned Parquet, broadcast joins, windows, Spark SQL and a measured performance lab.',
 'Spark 4 jobs on six months of NYC yellow-taxi trips: clean them into a month-partitioned dataset, analyse them with the DataFrame API and Spark SQL, and measure what partition pruning, join strategies, AQE, skew handling and caching actually change.',
 'Data pipelines', 'Days 50–58', '{"Spark 4",PySpark,Parquet}',
 '{"Every optimisation is timed against a baseline, with the query plans saved"}',
 'https://github.com/sasukeaizen7/portfolio/tree/main/06-pyspark', '#f87171', false, 7),
('orchestrated-marketing', 'Airflow + Spark + dbt',
 'Airflow orchestrates a Spark job and dbt models on 41,188 real bank-marketing calls.',
 'A weekly pipeline on the UCI Bank Marketing dataset. Python downloads, Spark cleans and partitions, Postgres stores, dbt models and tests, and Airflow orders, retries and monitors everything.',
 'Data pipelines', 'Days 59–63 · project 2', '{Airflow,Spark,dbt,Postgres}',
 '{"The dataset has no year column: Spark rebuilds it from row order and matches the documented range exactly"}',
 'https://github.com/sasukeaizen7/portfolio/tree/main/07-project-2-orchestrated', '#34d399', false, 8),
('data-lake', 'S3 data lake',
 'Raw, clean and results zones, a Glue-style job, a catalog crawler and least-privilege access on 1.05M bike trips.',
 'The core AWS data-lake pattern with free local stand-ins and the same S3 API: SeaweedFS for S3, DuckDB for Glue and Athena, and IAM-style policies proven by tests.',
 'Data pipelines', 'Days 64–70', '{S3,DuckDB,IAM,Parquet}',
 '{"Least-privilege access is proven by tests that expect access to be denied"}',
 'https://github.com/sasukeaizen7/portfolio/tree/main/08-data-lake', '#38bdf8', false, 9),
('kafka-streaming', 'Kafka streaming',
 'Producer → 3-partition topic → consumer group → Postgres, with exactly-once results and a dead-letter queue.',
 'A producer generates a realistic, messy clickstream. Kafka buffers it in a 3-partition topic and a consumer group of two writes it to Postgres with exactly-once results, a dead-letter queue and per-minute aggregates.',
 'Data pipelines', 'Days 71–77', '{Kafka,Python,Postgres}',
 '{"Replays after a crash insert nothing twice: aggregates always match the events"}',
 'https://github.com/sasukeaizen7/portfolio/tree/main/09-kafka-streaming', '#c084fc', false, 10),
('delta-medallion', 'Delta Lake medallion',
 'Bronze, silver and gold with MERGE, change data feed, schema evolution and time travel.',
 'Spark 4 and Delta Lake on a daily click export full of duplicates, late events and malformed lines. On day 3 the source starts sending a new field without warning, and the pipeline evolves the schema instead of breaking.',
 'Data pipelines', 'Days 78–84', '{"Delta Lake",Spark,Terraform,"GitHub Actions"}',
 '{"Incremental: each layer only reads what changed since its last run"}',
 'https://github.com/sasukeaizen7/portfolio/tree/main/10-medallion-delta', '#4ade80', false, 11);

-- The 18 SQL analytics projects (separate repository).
insert into projects (slug, title, summary, category, period, tags, repo_url, color, featured, sort_order)
select 'sql-' || substr(dir, 4), title, summary, 'SQL analytics', 'Days 1–9', tags,
       'https://github.com/sasukeaizen7/sql-projects/tree/main/projects/' || dir, color, featured, n
from (values
  (1,  '01-nyc-taxi-trips', 'NYC Taxi Trips', 'JFK alone brings in 14.3% of all taxi revenue. Includes 11 PostgreSQL index benchmarks.', '{DuckDB,PostgreSQL,Indexing}'::text[], '#fbbf24', true),
  (2,  '02-chinook-music-store', 'Chinook Music Store', '43% of the catalog has never sold. Full PK/FK model, recursive org chart, relational division.', '{SQL,"Data modeling"}', '#f59e0b', false),
  (3,  '03-online-retail-cohorts', 'Online Retail: Cohorts & RFM', '24% of customers make 80% of revenue. Cohorts, RFM, market basket, 9 index benchmarks.', '{SQL,Cohorts,RFM}', '#fb923c', true),
  (4,  '04-paris-real-estate', 'Paris Real Estate', 'Prices fell in all 20 arrondissements in 2024 (−5.6%).', '{SQL,DuckDB}', '#f97316', false),
  (5,  '05-paris-airbnb', 'Paris Airbnb', '1 entire home in 8 has no valid registration number.', '{SQL,Regex}', '#fdba74', false),
  (6,  '06-velib-paris', 'Vélib'' Paris stations', '4× fill gap between the 15e and the 18e; some stations silent since 2021.', '{SQL,"Live API"}', '#fcd34d', false),
  (7,  '07-ratp-metro-traffic', 'RATP Métro Traffic', 'Business districts recovered least after COVID (9e: 61%).', '{SQL,"Window functions"}', '#fde68a', false),
  (8,  '08-paris-trees', 'Paris Trees', 'Over half the street trees of the 5e–8e are one genus.', '{SQL}', '#bef264', false),
  (9,  '09-co2-emissions', 'CO₂ Emissions', 'Summing every row overcounts world CO₂ 6.4×.', '{SQL,"Data quality"}', '#fca5a5', false),
  (10, '10-energy-transition', 'Energy Transition', 'Wind + solar passed nuclear in 2021 and hydro in 2025.', '{SQL}', '#86efac', false),
  (11, '11-paris-climate', 'Paris Climate 1950–2025', '+0.42 °C per decade since 1980; 5× more 30 °C days.', '{SQL,"Time series"}', '#f87171', false),
  (12, '12-earthquakes', 'Earthquakes 2000–2025', 'Gutenberg–Richter b = 1.02 (R² 0.998), fitted in SQL.', '{SQL,"ASOF joins"}', '#fb7185', false),
  (13, '13-movielens-ratings', 'MovieLens Ratings', '296 movies have a "perfect" 5.0 average from 1–2 votes.', '{SQL}', '#e879f9', false),
  (14, '14-chicago-crimes', 'Chicago Crime 2024', '9,443 crimes carry a fake 00:00 timestamp.', '{SQL,"Data quality"}', '#f9a8d4', false),
  (15, '15-openflights-network', 'OpenFlights Network', '89% of the world''s airports are within 2 connections of Paris. Shortest paths in a recursive CTE.', '{SQL,"Recursive CTE",Graphs}', '#fde047', true),
  (16, '16-formula1-history', 'Formula 1, 1950–2026', 'Pole wins 43.6% of races; Verstappen won 86% in 2023.', '{SQL,"Gaps and islands"}', '#ef4444', false),
  (17, '17-french-first-names', 'French First Names', 'Top-10 names: 43% of babies in 1900, 9.6% in 2024.', '{SQL}', '#fda4af', false),
  (18, '18-france-road-accidents', 'Road Accidents in France', 'Rural roads: 38% of accidents, 68% of deaths.', '{SQL}', '#fed7aa', false)
) as t (n, dir, title, summary, tags, color, featured);
